services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bilpay-coin-dashboard
    ports:
      - "3000:3000"
    env_file:
      - .env.staging
    restart: always
